### ISSUE TITLE
Add tests for sumLinesOfArbitraryLengthFile

### ISSUE THREAD

**Issue by raq929** [ga-wdi-boston/node-promises-diagnostic#102]
[edited by @bengitscode - added description]

We should always strive to have tests but also the resolution of #103 involves using the number of passing tests to determine the score—something I know we'd like to be doing more, as much as we can.

**Comment by gaand** [comment]
Descriptions are required in issues. 

Also, why?

**Comment by raq929** [comment]
Because there aren't tests? I would rate this as _extremely_ not urgent.

**Comment by raq929** [comment]
Actually, I'm now confused about this diagnostic. I'm going to talk to @gaand or @jrhorn424 about it. `node-api-diagnostic` only had one question. This appears to have two, but I'm not sure it should. If it does, then I think we needs tests. If it doesn't, this function should be removed from the diagnostic.

**Comment by raq929** [comment]
OK. Upon further investigation (reviewing last cohorts PRs) it seems like we did not expect them to promisify this function. It is probably a consequence of #31. I am going to remove it for this iteration, and add a question that is inline with the objectives from `node-api-promises`

**Comment by raq929** [comment]
This is now a discussion in several issues; but. If we keep it, I think we should test it. :)
