### ISSUE TITLE
Confusion between "write" and "change" in diagnostic instructions

### ISSUE THREAD

**Issue by laurenfazah** [ga-wdi-boston/node-promises-diagnostic#57]
- @gaand

**Comment by gaand** [comment]
In `lib/diagnostic.js`

**Comment by jrhorn424** [comment]
b1f15f532c38281a038e9d200fa5c29d687fd947

**Comment by raq929** [comment]
I see Jeff's commit fixes the problem, but it's not on master, so I'm going to redo that.

**Comment by raq929** [comment]
Nevermind, I was looking at `node-api-diagnostic` instead. I'm closing this issue as the commit above resolves it.

**Comment by gaand** [comment]
I think this is a technical violation of process 🤖

**Comment by raq929** [comment]
Hmmm... If the process had been in place when the commit was made, the commit would have closed it, so I closed it. :)

**Comment by gaand** [comment]
@raq929 I believe the process is that issues closed with a commit on a pull request reviewed by a different member of the instructional staff are okay.  All other issues are closed by the opener or @jrhorn424 or me if that person is unavailable.  This is neither of those.  Closing issues is not the point.  Following process for process sake is not the point.  Not losing data is the point.  Developing a habit of following process makes losing data less likely. If you had asked me to close it with an @gaand I would have done so.  And the process would have been followed.  And it wouldn't have taken less time.
